name: kaimono_list
description: "A new Flutter project."

publish_to: "none"

version: 0.1.0+18

environment: { sdk: ^3.10.1 }

dependencies:
  animated_list_plus: ^0.5.2
  cloud_firestore: ^6.1.0
  collection: ^1.19.1
  fake_cloud_firestore: ^4.0.0
  firebase_auth: ^6.1.2
  firebase_analytics: ^12.0.4
  firebase_core: 4.2.1
  flutter: { sdk: flutter }
  flutter_hooks: ^0.21.3
  flutter_slidable: ^4.0.3
  form_builder_validators: ^11.2.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^15.2.4
  hooks_riverpod: ^3.0.3
  intersperse: ^2.0.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  recase: ^4.1.0
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.10.4
  build_verify: ^3.1.1
  cider: ^0.2.9
  custom_lint: ^0.8.1
  flutter_launcher_icons: ^0.14.4
  flutter_test: { sdk: flutter }
  freezed: ^3.2.3
  go_router_builder: ^4.1.3
  import_path_converter: ^1.0.1
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

import_path_converter:
  ignored_files:
    - \/test\/*
